# Generated by Django 2.2 on 2019-04-23 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tagi',
        ),
        migrations.AddField(
            model_name='tag',
            name='tagi',
            field=models.ManyToManyField(to='Produkty.Produkty'),
        ),
        migrations.AlterField(
            model_name='produkty',
            name='producent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producenci', to='Produkty.Producent'),
        ),
    ]
