# Generated by Django 2.2 on 2019-04-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0003_produkty_komentaz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tagi',
        ),
        migrations.AddField(
            model_name='produkty',
            name='tagi',
            field=models.ManyToManyField(to='Produkty.Tag'),
        ),
    ]
