# Generated by Django 2.2 on 2019-04-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0004_auto_20190423_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Komentaż', 'verbose_name_plural': 'Komentarze'},
        ),
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='producent',
            options={'verbose_name': 'Producent', 'verbose_name_plural': 'Producenci'},
        ),
        migrations.AlterModelOptions(
            name='produkty',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tagi'},
        ),
    ]
