# Generated by Django 2.2 on 2019-04-23 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0006_auto_20190423_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='kategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.Kategoria'),
        ),
        migrations.AlterField(
            model_name='produkty',
            name='komentaz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.Comment'),
        ),
    ]
