# Generated by Django 2.2 on 2019-04-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0007_auto_20190423_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='tagi',
            field=models.ManyToManyField(blank=True, null=True, to='Produkty.Tag'),
        ),
    ]
