# Generated by Django 2.2 on 2019-04-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0008_auto_20190423_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='producent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.Producent'),
        ),
    ]
