# Generated by Django 2.2 on 2019-05-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0009_auto_20190423_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkty',
            name='created',
        ),
        migrations.RemoveField(
            model_name='produkty',
            name='kategoria',
        ),
        migrations.RemoveField(
            model_name='produkty',
            name='komentaz',
        ),
        migrations.RemoveField(
            model_name='produkty',
            name='producent',
        ),
        migrations.RemoveField(
            model_name='produkty',
            name='tagi',
        ),
        migrations.RemoveField(
            model_name='produkty',
            name='updated',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Kategoria',
        ),
        migrations.DeleteModel(
            name='Producent',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
