# Generated by Django 2.2 on 2019-05-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0010_auto_20190501_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkty',
            options={},
        ),
    ]
