# Generated by Django 2.2.1 on 2019-05-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0014_auto_20190502_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkty',
            name='kategoria',
        ),
        migrations.DeleteModel(
            name='Kategoria',
        ),
    ]
